
local input_code = [[ ]]

local g = {}
g.info = {}
g.config = gg.EXT_CACHE_DIR .. "/bytecode_protector.cfg"

local function getAssembly(code)
    local chunk, err = load(code)
    if not chunk then return nil, err end
    
    local temp_file = gg.EXT_CACHE_DIR .. "/temp_asm.txt"
    local f = io.open(temp_file, "w")
    if f then f:close() end
    
    gg.internal2(chunk, temp_file)
    
    local asm_file = io.open(temp_file, "r")
    if not asm_file then return nil, "No assembly" end
    
    local asm = asm_file:read("*a")
    asm_file:close()
    
    return asm
end

local function createValidAssembly(code)
    local asm = getAssembly(code)
    if not asm then return nil end
    
    if not asm:find(".linedefined") then
        local header = [[
.source "protected_script.lua"
.linedefined 0
.lastlinedefined 0
.numparams 0
.is_vararg 0
.maxstacksize 250
]]
        asm = header .. asm
    end
    
    if not asm:find("Lua assembler file generated by") then
        asm = [[
.source "protected_script.lua"
]] .. asm
    end
    
    return asm
end

local function modifyAssembly(asm)
    local lines = {}
    local in_body = false
    
    for line in asm:gmatch("[^\n]+") do
        table.insert(lines, line)
        
        if line:match("^%.line") then
            in_body = true
        end
        
        if in_body and not line:match("^[%.%;]") and line ~= "" then
            if math.random(1, 3) == 1 then
                if math.random(1, 2) == 1 then
                    table.insert(lines, "LOADK v" .. math.random(240, 249) .. " 0")
                else
                    table.insert(lines, "MOVE v" .. math.random(240, 249) .. " v" .. math.random(240, 249))
                end
                
                if math.random(1, 4) == 1 then
                    local r1 = math.random(1000, 9999)
                    table.insert(lines, "JMP :goto_" .. r1)
                    table.insert(lines, ":goto_" .. r1)
                end
            end
        end
    end
    
    local result = table.concat(lines, "\n")
    
    result = result:gsub("(CALL[^\n]+)", function(match)
        local r1 = math.random(1000, 9999)
        local r2 = math.random(1000, 9999)
        return "JMP :goto_" .. r1 .. "\n:goto_" .. r1 .. "\n" .. match .. "\nJMP :goto_" .. r2 .. "\n:goto_" .. r2
    end)
    
    result = result:gsub("(RETURN[^\n]+)", "LOADK v247 0\n%1\nLOADK v248 0")
    
    result = result:gsub("%.numparams %d+", ".numparams 250")
    result = result:gsub("%.is_vararg %d+", ".is_vararg 250")
    result = result:gsub("%.maxstacksize %d+", ".maxstacksize 250")
    result = result:gsub("%.linedefined %d+", ".linedefined 250")
    result = result:gsub("%.lastlinedefined %d+", ".lastlinedefined 250")
    
    if result:find(".upval") then
        result = result:gsub("(%.upval[^\n]+)", "%1\nLOADK v249 0")
    end
    
    result = result:gsub("JMP :goto_(%d+)[^\n]*\n:goto_(%d+)", function(a, b)
        if a == b then return ":goto_" .. b end
        return "JMP :goto_" .. a .. "\n:goto_" .. b
    end)
    
    return result
end

local function assembleToBytecode(asm)
    local chunk, err = load(asm)
    if not chunk then return nil, err end
    
    local bytecode = string.dump(chunk, true)
    return bytecode
end

local function protectCode(code, output_file)
    --gg.toast("Reading...")
    
    if not code or code == "" then return false, "Empty code" end
    
    --gg.toast("Generating assembly...")
    
    local asm = createValidAssembly(code)
    if not asm then return false, "Failed to generate assembly" end
    
    --gg.toast("Modifying...")
    
    asm = modifyAssembly(asm)
    
    --gg.toast("Assembling bytecode...")
    
    local bytecode, err = assembleToBytecode(asm)
    if not bytecode then return false, "Assembly error: " .. (err or "") end
    
    --gg.toast("Saving...")
    
    local out = io.open(output_file, "wb")
    if not out then return false, "Error saving" end
    
    out:write(bytecode)
    out:close()
    
    return true
end

local function main()
    local output_path = gg.EXT_CACHE_DIR .. "/protected_output.lua"
    
    local ok, msg = protectCode(input_code, output_path)
            gg.alert(
                "PROTECTED\n\n" ..
                "Input: Code in variable\n" ..
                "Output: " .. output_path .. "\n\n" ..
                "Techniques applied:\n" ..
                "Header modification\n" ..
                "Instruction insertion\n" ..
                "Random JMP\n" ..
                "CALL obfuscation",
                "COMPLETED"
            )
    end
main()